version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - go-graphql-cli_network

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go-graphql-cli_network

volumes:  
  pgdata:

networks:
  go-graphql-cli_network:
    driver: "bridge"
