package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"go-graphql-cli/domain/models/graphql"
	"go-graphql-cli/infra/graph"
	"go-graphql-cli/usecase"
)

// GetEntries is the resolver for the getEntries field.
func (r *queryResolver) GetEntries(ctx context.Context) ([]*graphql.Entry, error) {
	return usecase.NewEntriesUseCase().GetEntries()
}

// GetEntry is the resolver for the getEntry field.
func (r *queryResolver) GetEntry(ctx context.Context, id string) (*graphql.Entry, error) {
	return usecase.NewEntriesUseCase().GetEntry(id)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
